import assert from 'node:assert/strict';
import './placement.js';
const {describe, screenDelta, tableDelta} = globalThis.PaperdollPlacement;
const sword = {id: 1, equipX: 14, equipY: 131};
const main = describe({slot: 'MainHand'}, sword, 0, {});
const off = describe({slot: 'OffHand'}, sword, 1, {});
assert.notEqual(main.key, off.key, 'Placement belongs to the body type and hand slot');
assert.notEqual(main.key, describe({slot: 'MainHand'}, sword, 1, {}).key);
assert.notEqual(main.key, describe({slot: 'OffHand'}, sword, 0, {}).key);
assert.equal(main.table, null, 'Local fitting must not edit shared item grip coordinates');
assert.deepEqual(tableDelta(main, 1, 0, false), [1, 0]);
assert.deepEqual(screenDelta(off, [1, 0], true), [1, 0], 'Arrows are screen-relative even on rotated weapons');
const armor = {id: 84};
const male = describe({slot: 'Armor'}, armor, 0, {84: {0: [47,78], 1: [50,93]}});
const female = describe({slot: 'Armor'}, armor, 1, {84: {0: [47,78], 1: [50,93]}});
assert.notEqual(male.key, female.key);
assert.deepEqual(male.base, [47,78]);
assert.deepEqual(tableDelta(male, 0, 1, false), [0,1]);
const bow = describe({slot: 'Bow'}, {id: 56}, 0, {});
assert.equal(bow.table, null, 'Bow moves must not claim an unused equipX/Y table patch');
console.log('Placement coordinate tests passed');
