// Generated by level_generation/ui/obsidian_rest_hourglass_20260929/export_runtime.mjs.
// Regenerate with the approved sand-volume.mjs geometry; do not edit atlas dimensions separately.
#pragma once

namespace OpenYAMM::Game::RestHourglassAtlas
{
inline constexpr float drainSeconds = 8.0f;
inline constexpr float turnSeconds = 1.0f;
inline constexpr int framesPerOrientation = 129;
inline constexpr int canvasWidth = 144;
inline constexpr int canvasHeight = 216;
inline constexpr int cropX = 36;
inline constexpr int cropY = 42;
inline constexpr int cropWidth = 72;
inline constexpr int cropHeight = 132;
inline constexpr int padding = 2;
inline constexpr int columns = 16;
inline constexpr int rows = 17;
inline constexpr int frameWidth = 256;
inline constexpr int frameHeight = 384;
inline constexpr int cellWidth = 76;
inline constexpr int cellHeight = 136;
inline constexpr int atlasWidth = 1216;
inline constexpr int atlasHeight = 2312;
}
